### Build a one-column matrix

In [1]:
import numpy as np
vector = np.array([1,2,3,4,5])
row_vector = vector.reshape((5,1))
column_vector = vector.reshape((1,5))
single_feature_matrix = vector.reshape((1,5))

In [2]:
vector

array([1, 2, 3, 4, 5])

In [3]:
column_vector

array([[1, 2, 3, 4, 5]])

In [4]:
single_feature_matrix

array([[1, 2, 3, 4, 5]])